baseURL = "https://ccolladosoto.github.io"
languageCode = "es"
title = "Portfolio Clarita"
theme = "hugo-digital-garden-theme"

copyright = "Clara Collado Soto ©"

[params]
  name = "Clara Collado Soto"
  description = "Periodista en ciernes."
  initials = "CC"
  googleAnalytics = ""

  [[params.social]]
    name = "Twitter"
    link = "https://twitter.com/"
    icon = "fab fa-twitter"

  [[params.social]]
    name = "Github"
    link = "https://github.com/ccolladosoto"
    icon = "fab fa-github"

  [[params.social]]
    name = "Medium" 
    link = "#"
    icon = "fab fa-medium-m"

  [[params.social]]
    name = "LinkedIn"
    link = "#"
    icon = "fab fa-linkedin-in"


[menu]
  [[menu.main]]
    name = "Digital Garden"
    url = "/garden/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "Library"
    url = "/library/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[taxonomies]
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'
  library_tags = 'library_tags'

[markup]
  defaultMarkdownHandler = 'goldmark'

  [markup.goldmark.renderer]
    unsafe = true

  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true

  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'
