baseURL = "https://ccolladosoto.github.io"
languageCode = "es"
title = "Portfolio Clarita"
theme = "hugo-digital-garden-theme"

copyright = "Clara Collado Soto ©"

[params]
  name = "Clara Collado Soto"
  description = "Periodista en ciernes."
  initials = "CC"
  googleAnalytics = ""

  # Available icons can be searched at: https://fontawesome.com/icons
  [[params.social]]
    name = "Twitter"
    link = "https://twitter.com/"
    icon = "fab fa-twitter"

  [[params.social]]
    name = "Spotify"
    link = "https://www.spotify.com/es/premium/"
    icon = "fab fa-spotify"

  # [[params.social]]
  #   name = "Github"
  #   link = "https://github.com/ccolladosoto"
  #   icon = "fab fa-github"

  # [[params.social]]
  #   name = "Medium" 
  #   link = "#"
  #   icon = "fab fa-medium-m"

  # [[params.social]]
  #   name = "LinkedIn"
  #   link = "#"
  #   icon = "fab fa-linkedin-in"


[menu]
  # [[menu.main]]
  #   name = "Digital Garden"
  #   url = "/garden/"
  #   weight = 1

  [[menu.main]]
    name = "Artículos"
    url = "/projects/"
    weight = 2

  # [[menu.main]]
  #   name = "Library"
  #   url = "/library/"
  #   weight = 3

  [[menu.main]]
    name = "Sobre mi"
    url = "/about/"
    weight = 4

[taxonomies]
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'
  library_tags = 'library_tags'

[markup]
  defaultMarkdownHandler = 'goldmark'

  [markup.goldmark.renderer]
    unsafe = true

  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true

  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'
